### ISSUE TITLE
Avatar component doesn't show upload previews correctly when there are multiple avatar components on a page

### ISSUE THREAD

**Issue by ProMcTagonist** [Gixx/mdl-kvl#9]
**Reproduce:**

 * Have multiple avatar components on a page.

 * In the first, choose a file to upload, then click checkmark.

 * In the second, choose a different file to upload, then click checkmark.

**Expected result:** 

Each avatar component shows a preview of its own file-to-be-uploaded. 

**Actual Result:**

The first avatar component shows a preview of the file-to-be-uploaded as usual.

The second avatar component shows a preview for the file that was selected in the first one.

------

I've reproduced this on your site:

http://mdl.gixx-web.com/components-ext.html#cards-section

as well as on mine, using the latest version of mdl-components-ext from this repo. Reproducible in every browser I've tried (Chrome and Fx on desktop, Chrome and Fx on mobile, Safari on mobile).

**Comment by Gixx** [comment]
Thanks for the bug report. I'll check it...

Best,
Gabor

2017. jan. 13. 23:12 ezt írta ("ProMcTagonist" <notifications@github.com>):

*Reproduce:*

   -

   Have multiple avatar components on a page.
   -

   In the first, choose a file to upload, then click checkmark.
   -

   In the second, choose a different file to upload, then click checkmark.

*Expected result:*

Each avatar component shows a preview of its own file-to-be-uploaded.

*Actual Result:*

The first avatar component shows a preview of the file-to-be-uploaded as
usual.

The second avatar component shows a preview for the file that was selected
in the first one.
------------------------------

I've reproduced this on your site:

http://mdl.gixx-web.com/components-ext.html#cards-section

as well as on mine, using the latest version of mdl-components-ext from
this repo.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Gixx/mdl-components-ext/issues/9>, or mute the thread

**Comment by Gixx** [comment]
Hi,

I found and fixed the issue. The demo website will be updated later today - I can do it from how only - but the sources and the package are here on GitHub:

https://github.com/Gixx/mdl-components-ext/tree/master/package

Please check it. Thanks for reporting the error and I hope you enjoy my extensions ;)


Best,
Gabor

**Comment by ProMcTagonist** [comment]
Thanks, everything's working now :)
